### ISSUE TITLE
Make /review with proj id arg throw no errors

### ISSUE THREAD

**Issue by tannerwelsh** [LearnersGuild/game-cli#43] opened 2016-07-05 15:56 UTC
`/review #project-id` throws

```
*Error:* Invalid arguments. Try `--help` for usage.. Try `--help` for usage.
```

Instead it should summarize the review for the project.

**Comment by bundacia** [comment] 2016-07-05 16:11
This is a duplicate of https://github.com/LearnersGuild/game-cli/issues/42

We just haven't implemented that functionality yet.

**Closed by bundacia** 2016-07-05 16:11 UTC
Labels: bug
